version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/pgdata

  neoark-api:
    build:
        context: .
        dockerfile:  ./docker/neoark-api/Dockerfile
    environment:
      NODE_ENV: development
      ELASTICSEARCH_NODE: http://elk:9200
      NODE_ENV: development
      OKTA_TOKEN: $OKTA_TOKEN
      OKTA_HOST: $OKTA_HOST
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    volumes:
      - ./packages/neoark-api:/home/node
    ports:
      - "${PORT_DEV}:9000"
    depends_on:
      - postgres
      - elk

  # neoark-api-prod:
  #   build: ./packages/neoark-api
  #   environment:
  #     NODE_ENV: production
  #     ELASTICSEARCH_NODE: http://elk:9200
  #     POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
  #     OKTA_TOKEN: $OKTA_TOKEN
  #     OKTA_HOST: $OKTA_HOST
  #   ports:
  #     - "${PORT_PROD}:9000"
  #   depends_on:
  #     - postgres
  #     - elk

  elk:
    image: sebp/elk
    ports:
      - "5601:5601" # Kibana web interface
      - "9200:9200" # Elasticsearch JSON interface
      - "5044:5044" # Logstash Beats interface
    volumes:
      - ./.elk-data:/var/lib/elasticsearch


