version: '3'

services:
  mongo:
    image: mongo:3.6-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
      MONGO_INITDB_DATABASE: $MONGO_DB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./.mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
      JWT_SECRET: $JWT_SECRET
      NODE_ENV: development
      ELASTICSEARCH_NODE: http://elk:9200
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}
      NODE_ENV: development
    volumes:
      - ./:/home/node
    ports:
      - "${PORT_DEV}:9000"
    depends_on:
      - mongo
      - elk

  app-prod:
    build: .
    environment:
      JWT_SECRET: $JWT_SECRET
      NODE_ENV: development
      ELASTICSEARCH_NODE: http://elk:9200
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}
    ports:
      - "${PORT_PROD}:9000"
    depends_on:
      - mongo
      - elk

  elk:
    image: sebp/elk
    ports:
      - "5601:5601" # Kibana web interface
      - "9200:9200" # Elasticsearch JSON interface
      - "5044:5044" # Logstash Beats interface
    volumes:
      - ./.elk-data:/var/lib/elasticsearch


