name: Neoark Front CI

on:
  push:
    paths:
    - 'packages/neoark-front/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install, lint, and test
        run: |
          yarn --pure-lockfile
          npx lerna bootstrap
          npx lerna exec --scope neoark-front -- yarn lint
          npx lerna exec --scope neoark-front -- yarn test

      - name: Codecov GitHub Action
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./packages/neoark-front/coverage/clover.xml #optional
          flags: neoark_front #optional
          fail_ci_if_error: true #optional (default = false)
